version: "3.8"

services:
  node_service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    volumes:
      - .:/home/node/app
