FROM node:17.3.0

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package.json ./

COPY --chown=node:node yarn.lock ./

RUN yarn install

COPY --chown=node:node . .

RUN yarn run build

EXPOSE 3001

CMD ["yarn", "run", "start"]
